Repository cloudforet-io/charts, pull requests merged in 2024-04, with the labels that each got.

#48 feat: Updated the timezone from utc-0 to UTC.
  examples/initializer.yaml
Labels: fail/signedoff

#52 Solve metrics receiver transfrom resource nil error
  charts/k8s-monitoring/values.yaml
Labels: bug, pass/signedoff

#53 Solve invalid type. Expected: array, given: string
  charts/k8s-monitoring/values.yaml
Labels: bug, pass/signedoff

#55 Add helm pacakaging and publish
  .github/workflows/publish.yaml
Labels: fail/signedoff

#58 Add Automate Helm chart packaging and release with GitHub Actions
  .github/workflows/publish.yaml
Labels: enhancement

#59 Fix indentation
  .github/workflows/publish.yaml
Labels: bug, pass/signedoff

#60 Fix chart_name and chart_version's newline
  .github/workflows/publish.yaml
Labels: bug, pass/signedoff

#62 Add helm packaging and publish to gh-pages
  .github/workflows/publish.yaml
Labels: enhancement, pass/signedoff

#63 Update gh-pages
  .github/workflows/check-pull-request.yml
  .github/workflows/dispatch_sync_ci.yaml
  .gitignore
  README.md
  docs/images/aws_architecture.png
  docs/images/cloudforet_architecture.png
  docs/images/on_premise_architecture.png
  docs/images/port_forwarding_architecture.png
  docs/ingress/aws.md
  docs/ingress/on_premise.md
  docs/ingress/port_forwarding.md
  docs/parameters.md
  examples/ingress/aws/console_ingress.yaml
  examples/ingress/aws/grpc_api_ingress.yaml
  examples/ingress/aws/monitoring_webhook_ingress.yaml
  examples/ingress/aws/rest_api_ingress.yaml
  examples/ingress/on_premise/certificate_secret.yaml
  examples/ingress/on_premise/console_ingress.yaml
  examples/ingress/on_premise/grpc_api_ingress.yaml
  examples/ingress/on_premise/monitoring_webhook_ingress.yaml
  examples/ingress/on_premise/rest_api_ingress.yaml
  examples/initializer.yaml
  examples/rbac.yaml
  examples/values/atlas_db_values.yaml
  examples/values/change_db_name_values.yaml
  examples/values/change_namespace_values.yaml
  examples/values/change_pod_replica_values.yaml
  examples/values/external_db_values.yaml
  examples/values/minimum.yaml
  examples/values/multi_tenancy_mode_values.yaml
  examples/values/node_selector_values.yaml
  examples/values/one_namespace_values.yaml
  examples/values/set_opentelemetry_values.yaml
Labels: pass/signedoff

#66 Fix test profiles
  charts/k8s-monitoring/values.yaml
Labels: enhancement, pass/signedoff

#67 Fix test receiver.transforms
  charts/k8s-monitoring/values.yaml
Labels: pass/signedoff

#68 Update grafana/k8s-monitoring:0.13.4
  charts/k8s-monitoring/Chart.lock
  charts/k8s-monitoring/Chart.yaml
  charts/k8s-monitoring/README.md
  charts/k8s-monitoring/charts/grafana-agent/CHANGELOG.md
  charts/k8s-monitoring/charts/grafana-agent/Chart.lock
  charts/k8s-monitoring/charts/grafana-agent/Chart.yaml
  charts/k8s-monitoring/charts/grafana-agent/README.md
  charts/k8s-monitoring/charts/grafana-agent/ci/nonroot-values.yaml
  charts/k8s-monitoring/charts/opencost/Chart.yaml
  charts/k8s-monitoring/charts/opencost/README.md
  charts/k8s-monitoring/charts/opencost/README.md.gotmpl
  charts/k8s-monitoring/charts/opencost/templates/deployment.yaml
  charts/k8s-monitoring/charts/opencost/values.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/Chart.lock
  charts/k8s-monitoring/charts/prometheus-operator-crds/Chart.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagers.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/charts/crds/templates/crd-podmonitors.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/charts/crds/templates/crd-probes.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusagents.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/charts/crds/templates/crd-prometheuses.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/charts/crds/templates/crd-prometheusrules.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/charts/crds/templates/crd-scrapeconfigs.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/charts/crds/templates/crd-servicemonitors.yaml
  charts/k8s-monitoring/charts/prometheus-operator-crds/charts/crds/templates/crd-thanosrulers.yaml
  charts/k8s-monitoring/docs/HelmTests.md
  charts/k8s-monitoring/docs/Troubleshooting.md
  charts/k8s-monitoring/templates/agent_config/_profiles_ebpf.river.txt
  charts/k8s-monitoring/templates/agent_config/_profiles_pprof.river.txt
  charts/k8s-monitoring/values.yaml
Labels: enhancement, pass/signedoff

#69 Update api-server state
  charts/k8s-monitoring/values.yaml
Labels: enhancement
